[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = qio
board_build.partitions = huge_app.csv

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library